const {

    API_KEY , PROJECT_ID , DATABASE_ID , PATIENT_COLLECTION_ID , DOCTOR_COLLECTION_ID , 
    APPOINTMENT_COLLECTION_ID,
    NEXT_PUBLIC_BUCKET_ID: BUCKET_ID,
    NEXT_ENDPOINT_ID : ENDPOINT,

    
} = process.env;